name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3

    - name: Run pre-commit hooks
      uses: pre-commit/action@v3.0.1

  # Setup job to cache dependencies for faster CI runs
  setup:
    name: Setup dependencies
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout reactor-uc
      uses: ./.github/actions/reactor-uc

    - name: Install LFC dependencies
      uses: ./reactor-uc/.github/actions/lingua-franca

  ci:
    name: Run tests
    needs: [setup, pre-commit]
    runs-on: ubuntu-24.04
    env:
      REACTOR_UC_PATH: ${{ github.workspace }}/reactor-uc
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout reactor-uc
      uses: ./.github/actions/reactor-uc

    - name: Install LFC dependencies
      uses: ./reactor-uc/.github/actions/lingua-franca

    - name: Run tests
      run: ./.github/scripts/run-all.sh
